version: "3.7"

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jaeger
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/bin/tmp/postgres:/var/lib/postgresql/data

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "16686:16686"
#    environment:
#      - SPAN_STORAGE_TYPE=grpc-plugin
#      - GRPC_STORAGE_PLUGIN_BINARY=/opt/jaeger-postgres-storage
#      - GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE=/opt/config.yaml
#      - GRPC_STORAGE_PLUGIN_LOG_LEVEL=debug
#    volumes:
#      - ${PWD}/bin/jaeger-postgres-storage:/opt/jaeger-postgres-storage
#      - ${PWD}/hack/config.yaml:/opt/config.yaml
#    depends_on:
#      - postgres

  hotrod:
    network_mode: host
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=localhost
      - JAEGER_AGENT_PORT=6831
#    depends_on:
#      - jaeger

